/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.CiudadDAO;
import model.CiudadVO;
import model.TemperaturaDAO;
import model.TemperaturaVO;
import model.Meses;
import model.MesesDAO;
import javax.swing.JOptionPane;
import model.ControladorFecha;

/**
 *
 * @author joseb
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    DefaultComboBoxModel modeloCombo;
    DefaultComboBoxModel modeloCombo2;
    DefaultListModel modeloLista;
    DefaultTableModel modeloTabla;

    public View(DefaultComboBoxModel modeloCombo, DefaultListModel modeloLista, JButton btnVer, JComboBox<String> cmbMeses, JLabel jLabel1, JLabel jLabel2, JLabel jLabel3, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JScrollPane jScrollPane3, JTable jTable1, JList<String> lstCiudades, JTable tablaTemperaturas, JTextField txtAnio) throws HeadlessException {
        this.modeloCombo = modeloCombo;
        this.modeloLista = modeloLista;
        this.btnVer = btnVer;
        this.cmbMeses = cmbMeses;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.jScrollPane3 = jScrollPane3;
        this.jTable1 = jTable1;
        this.lstCiudades = lstCiudades;
        this.tablaTemperaturas = tablaTemperaturas;
        this.txtAnio = txtAnio;
    }
    
    public View() {   
        initComponents();
        setRadios();
        // Ver Temperaturas
        setComboVer();
        setListVer();
        setTablaVer();
        // Cargar Temperaturas
        setComboCargar();
    }
    
    private void setComboCargar() {
        modeloCombo = new DefaultComboBoxModel();
        cmbCiudades.setModel(modeloCombo);
        
        CiudadDAO objCiudades = new CiudadDAO();
        ArrayList<CiudadVO> al = objCiudades.getNombresCiudades();
        for(CiudadVO r : al) {
            modeloCombo.addElement(r);
        }
    }  
    
    private void setComboVer() {
        modeloCombo2 = new DefaultComboBoxModel();
        cmbMeses.setModel(modeloCombo2);
        
        MesesDAO MesDAO = new MesesDAO();
     
        ArrayList<Meses> alMeses = MesDAO.getMeses();
        
        for(Meses mes : alMeses) {
            modeloCombo2.addElement(mes);
        }
    }
    
    private void setListVer() {
        modeloLista = new DefaultListModel();
        lstCiudades.setModel(modeloLista);
        
        CiudadDAO ciudad = new CiudadDAO();
        
        ArrayList<CiudadVO> alCiudades = ciudad.getAll();
        
        for(CiudadVO city : alCiudades) {
            modeloLista.addElement(city);
        }
    }
    
    private void setTablaVer() {
        modeloTabla = new DefaultTableModel();  
        tablaTemperaturas.setModel(modeloTabla);
        modeloTabla.addColumn("DIA");
        modeloTabla.addColumn("TEMPERATURA MINIMA");
        modeloTabla.addColumn("TEMPERATURA MAXIMA");
    }
    
    private void setRadios(){
        btngroupBotones.add(rbVer);
        btngroupBotones.add(rbCargar);
        rbVer.setSelected(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btngroupBotones = new javax.swing.ButtonGroup();
        panelVer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTemperaturas = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();
        txtAnio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbMeses = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCiudades = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbVer = new javax.swing.JRadioButton();
        rbCargar = new javax.swing.JRadioButton();
        panelCargar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbCiudades = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMinima = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaxima = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelVer.setBorder(javax.swing.BorderFactory.createTitledBorder("Ver Temperaturas"));

        tablaTemperaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTemperaturas.setFocusable(false);
        jScrollPane3.setViewportView(tablaTemperaturas);

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnioKeyTyped(evt);
            }
        });

        jLabel3.setText("Ingresar año");

        cmbMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Seleccionar mes");

        lstCiudades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCiudades);

        jLabel1.setText("Ciudades");

        javax.swing.GroupLayout panelVerLayout = new javax.swing.GroupLayout(panelVer);
        panelVer.setLayout(panelVerLayout);
        panelVerLayout.setHorizontalGroup(
            panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(panelVerLayout.createSequentialGroup()
                        .addGroup(panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbMeses, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelVerLayout.setVerticalGroup(
            panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelVerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVer)
                        .addGap(3, 3, 3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbVer.setText("Ver Temperaturas");
        rbVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerActionPerformed(evt);
            }
        });

        rbCargar.setText("Cargar Temperaturas");
        rbCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCargar)
                    .addComponent(rbVer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rbVer)
                .addGap(12, 12, 12)
                .addComponent(rbCargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCargar.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargar Temperatura"));
        panelCargar.setEnabled(false);

        jLabel4.setText("Seleccionar Ciudad");

        cmbCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCiudades.setEnabled(false);

        jLabel5.setText("Ingresar fecha (dd-mm-aaaa)");

        txtFecha.setEnabled(false);

        jLabel6.setText("Ingresar minima");

        txtMinima.setEnabled(false);
        txtMinima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinimaKeyTyped(evt);
            }
        });

        jLabel7.setText("Ingresar maxima");

        txtMaxima.setEnabled(false);
        txtMaxima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaximaKeyTyped(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.setEnabled(false);
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCargarLayout = new javax.swing.GroupLayout(panelCargar);
        panelCargar.setLayout(panelCargarLayout);
        panelCargarLayout.setHorizontalGroup(
            panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarLayout.createSequentialGroup()
                        .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCargarLayout.createSequentialGroup()
                                .addComponent(txtMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelCargarLayout.createSequentialGroup()
                        .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(cmbCiudades, 0, 232, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(txtFecha))
                            .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCargarLayout.setVerticalGroup(
            panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCargar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        modeloTabla.setNumRows(0);
        
        TemperaturaDAO TemperaturasOBJ = new TemperaturaDAO();
        
        ArrayList<TemperaturaVO> Temperaturas;
          
        MesesDAO MesDAO = new MesesDAO();       
        
        String fechaConsulta = txtAnio.getText() + "-" + MesDAO.devolverIdMes(modeloCombo2.getSelectedItem().toString()) + "%";
        
        Temperaturas = TemperaturasOBJ.getTemperaturas(lstCiudades.getSelectedIndex() + 1, fechaConsulta);
        
        
        TemperaturaDAO objDAO = new TemperaturaDAO();
        ArrayList<TemperaturaVO> al = objDAO.getTemperaturas(lstCiudades.getSelectedIndex() + 1, fechaConsulta);
        for(TemperaturaVO p : al) {
            
            Object[] row = new Object[3];
            
            row[0] = p.getFecha().substring(8,10);
            row[1] = p.getMinima();
            row[2] = p.getMaxima();
            
            modeloTabla.addRow(row);
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void rbVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerActionPerformed
        if (rbVer.isSelected()) {
            // Panel ver
            panelVer.setEnabled(true);
            lstCiudades.setEnabled(true);
            cmbMeses.setEnabled(true);
            txtAnio.setEnabled(true);
            btnVer.setEnabled(true);
            tablaTemperaturas.setEnabled(true);
            // Panel Cargar
            panelCargar.setEnabled(false);
            cmbCiudades.setEnabled(false);
            txtFecha.setEnabled(false);
            txtMinima.setEnabled(false);
            txtMaxima.setEnabled(false);
            btnCargar.setEnabled(false);
        } else {
            //Panel Ver
            panelVer.setEnabled(false);
            lstCiudades.setEnabled(false);
            cmbMeses.setEnabled(false);
            txtAnio.setEnabled(false);
            btnVer.setEnabled(false);
            tablaTemperaturas.setEnabled(false); 
            //Panel Cargar
            panelCargar.setEnabled(true);
            cmbCiudades.setEnabled(true);
            txtFecha.setEnabled(true);
            txtMinima.setEnabled(true);
            txtMaxima.setEnabled(true);
            btnCargar.setEnabled(true);
        }
    }//GEN-LAST:event_rbVerActionPerformed

    private void rbCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCargarActionPerformed
        if (rbCargar.isSelected()) {
            // Panel ver
            panelVer.setEnabled(false);
            lstCiudades.setEnabled(false);
            cmbMeses.setEnabled(false);
            txtAnio.setEnabled(false);
            btnVer.setEnabled(false);
            tablaTemperaturas.setEnabled(false);
            // Panel Cargar
            panelCargar.setEnabled(true);
            cmbCiudades.setEnabled(true);
            txtFecha.setEnabled(true);
            txtMinima.setEnabled(true);
            txtMaxima.setEnabled(true);
            btnCargar.setEnabled(true);
        } else {
            //Panel Ver
            panelVer.setEnabled(true);
            lstCiudades.setEnabled(true);
            cmbMeses.setEnabled(true);
            txtAnio.setEnabled(true);
            btnVer.setEnabled(true);
            tablaTemperaturas.setEnabled(true); 
            //Panel Cargar
            panelCargar.setEnabled(false);
            cmbCiudades.setEnabled(false);
            txtFecha.setEnabled(false);
            txtMinima.setEnabled(false);
            txtMaxima.setEnabled(false);
            btnCargar.setEnabled(false);
        }
    }//GEN-LAST:event_rbCargarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        
        try {
            int Ciudad = cmbCiudades.getSelectedIndex() + 1;
        
            String Fecha = txtFecha.getText();

            String Dia = Fecha.substring(0,2);
            String Mes = Fecha.substring(3,5);

            String Anio = Fecha.substring(6,10);
            

            String Minima = txtMinima.getText();

            String Maxima = txtMaxima.getText();
            
            int intMinima = Integer.parseInt(Minima);
            int intMaxima = Integer.parseInt(Maxima);

            TemperaturaDAO objCiudad = new TemperaturaDAO();
            
            ControladorFecha controlFecha = new ControladorFecha();
            
            Fecha = Anio + Mes + Dia;

            if (controlFecha.fechaCorrecta(txtFecha.getText()) && intMinima < intMaxima){
                if (!objCiudad.existeTemperatura(Ciudad, Fecha)){
                    objCiudad.grabarTemperaturas(Ciudad, Fecha, Minima, Maxima);
                    JOptionPane.showMessageDialog(null, "Datos cargados correctamente", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Registro ya existente", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                if (intMinima > intMaxima) {
                    JOptionPane.showMessageDialog(null, "La temperatura minima no puede ser mayor a la maxima", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Revise la fecha", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            System.out.println(objCiudad.existeTemperatura(Ciudad, Fecha));
        } catch(Exception ex) {
                JOptionPane.showMessageDialog(null, "Revise los datos ingresados", "InfoBox: " + "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnCargarActionPerformed

    private void txtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnioKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAnioKeyTyped

    private void txtMinimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinimaKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMinimaKeyTyped

    private void txtMaximaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaximaKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMaximaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnVer;
    private javax.swing.ButtonGroup btngroupBotones;
    private javax.swing.JComboBox<String> cmbCiudades;
    private javax.swing.JComboBox<String> cmbMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstCiudades;
    private javax.swing.JPanel panelCargar;
    private javax.swing.JPanel panelVer;
    private javax.swing.JRadioButton rbCargar;
    private javax.swing.JRadioButton rbVer;
    private javax.swing.JTable tablaTemperaturas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMaxima;
    private javax.swing.JTextField txtMinima;
    // End of variables declaration//GEN-END:variables
}
